# Generated by Django 4.1.6 on 2023-02-13 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('wood', models.IntegerField()),
                ('rock', models.IntegerField()),
                ('iron', models.IntegerField()),
                ('grain', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Men', 'Men'), ('Elves', 'Elves'), ('Dwarves', 'Dwarves'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor'), ('Goblins', 'Goblins')], max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Troops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('type', models.CharField(max_length=70)),
                ('health', models.IntegerField()),
                ('damage', models.FloatField()),
                ('speed', models.FloatField()),
                ('wood', models.IntegerField()),
                ('rock', models.IntegerField()),
                ('iron', models.IntegerField()),
                ('grain', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.race')),
            ],
        ),
        migrations.CreateModel(
            name='UserTroops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('level', models.FloatField(default=1.0)),
                ('troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.troops')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buildings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood', models.IntegerField(default=800)),
                ('rock', models.IntegerField(default=800)),
                ('iron', models.IntegerField(default=800)),
                ('grain', models.IntegerField(default=800)),
                ('token', models.IntegerField(default=0)),
                ('last_checkout', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('Wood', 'Wood'), ('Rock', 'Rock'), ('Iron', 'Iron'), ('Grain', 'Grain')], max_length=50)),
                ('offer_amount', models.IntegerField()),
                ('target_type', models.CharField(choices=[('Wood', 'Wood'), ('Rock', 'Rock'), ('Iron', 'Iron'), ('Grain', 'Grain')], max_length=50)),
                ('target_amount', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('offer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ManyToManyField(related_name='sender_user', to=settings.AUTH_USER_MODEL)),
                ('target', models.ManyToManyField(related_name='targer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locx', models.IntegerField()),
                ('locy', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.race'),
        ),
    ]
