# Generated by Django 4.1.6 on 2023-02-13 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infantry_kill', models.IntegerField()),
                ('pikeman_kill', models.IntegerField()),
                ('archer_kill', models.IntegerField()),
                ('cavalry_kill', models.IntegerField()),
                ('siege_kill', models.IntegerField()),
                ('infantry_dead', models.IntegerField()),
                ('pikeman_dead', models.IntegerField()),
                ('archer_dead', models.IntegerField()),
                ('cavalry_dead', models.IntegerField()),
                ('siege_dead', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
