# Generated by Django 4.1.6 on 2023-02-14 23:35a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troops',
            name='type',
            field=models.CharField(choices=[('infantry', 'infantry'), ('pike', 'pike'), ('archer', 'archer'), ('cavalry', 'cavalry'), ('siege', 'siege'), ('monster', 'monster')], max_length=70),
        ),
    ]
