# Generated by Django 4.1.6 on 2023-02-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_buildings_health'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildings',
            old_name='rock',
            new_name='stone',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='rock',
            new_name='stone',
        ),
        migrations.RenameField(
            model_name='troops',
            old_name='rock',
            new_name='stone',
        ),
        migrations.AlterField(
            model_name='market',
            name='offer_type',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Stone', 'Stone'), ('Iron', 'Iron'), ('Grain', 'Grain')], max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='target_type',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Stone', 'Stone'), ('Iron', 'Iron'), ('Grain', 'Grain')], max_length=50),
        ),
    ]
