# Generated by Django 4.1.6 on 2023-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_last_chekout_usertroops_last_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertroops',
            name='time_passed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
