# Generated by Django 4.1.6 on 2023-02-19 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usertroops_time_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='update_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbuildings',
            name='last_checkout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbuildings',
            name='time_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
