# Generated by Django 4.1.6 on 2023-02-22 11:55a

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_messages_delete_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
