# Generated by Django 4.1.6 on 2023-02-22 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_messages_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='target',
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='target',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
