# Generated by Django 4.1.6 on 2023-02-24 19:59a

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_buildings_race2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuildings',
            name='training_checkout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbuildings',
            name='training_time_passed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbuildings',
            name='training_troops',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
