# Generated by Django 4.1.6 on 2023-02-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_usertrooptraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='sorting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
