# Generated by Django 4.1.6 on 2023-02-25 23:49a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_buildings_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='troops',
            name='prerequisite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
