# Generated by Django 4.1.6 on 2023-02-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_troops_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(default='Middle Earth', max_length=30),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Men', 'Men'), ('Elves', 'Elves'), ('Dwarves', 'Dwarves'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor'), ('Goblins', 'Goblins'), ('Wild', 'Wild')], max_length=100),
        ),
        migrations.AlterField(
            model_name='troops',
            name='race',
            field=models.CharField(choices=[('Men', 'Men'), ('Elves', 'Elves'), ('Dwarves', 'Dwarves'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor'), ('Goblins', 'Goblins'), ('Wild', 'Wild')], max_length=80),
        ),
    ]
