# Generated by Django 4.1.6 on 2023-02-26 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_location_location_name_alter_race_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userbuildings'),
        ),
        migrations.CreateModel(
            name='TroopUpgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_carrier', models.PositiveIntegerField(default=0)),
                ('forge_blade', models.PositiveIntegerField(default=0)),
                ('heavy_armor', models.PositiveIntegerField(default=0)),
                ('arrow', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
