# Generated by Django 4.1.6 on 2023-02-27 20:27a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_troopupgrades_upgrading_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertroops',
            old_name='level',
            new_name='defence_level',
        ),
        migrations.AddField(
            model_name='usertroops',
            name='attack_level',
            field=models.FloatField(default=1.0),
        ),
    ]
