# Generated by Django 4.1.6 on 2023-02-28 20:16a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Men', 'Men'), ('Elves', 'Elves'), ('Dwarves', 'Dwarves'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor'), ('Goblins', 'Goblins'), ('Wild', 'Wild'), ('Wild2', 'Wild2')], max_length=100),
        ),
    ]
