# Generated by Django 4.1.6 on 2023-03-01 09:03a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='race',
            field=models.CharField(choices=[('Men', 'Men'), ('Elves', 'Elves'), ('Dwarves', 'Dwarves'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor'), ('Goblins', 'Goblins'), ('Wild', 'Wild'), ('Wild2', 'Wild2')], max_length=80),
        ),
        migrations.AlterField(
            model_name='troops',
            name='race',
            field=models.CharField(choices=[('Men', 'Men'), ('Elves', 'Elves'), ('Dwarves', 'Dwarves'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor'), ('Goblins', 'Goblins'), ('Wild', 'Wild'), ('Wild2', 'Wild2')], max_length=80),
        ),
    ]
