# Generated by Django 4.1.6 on 2023-03-10 13:51a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_buildings_race_alter_troops_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='troops',
            name='crash_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
