# Generated by Django 4.1.6 on 2023-03-11 23:36a

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0032_troops_crash_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('race', models.CharField(choices=[('Men', 'Men'), ('Elves', 'Elves'), ('Dwarves', 'Dwarves'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor'), ('Goblins', 'Goblins'), ('Wild', 'Wild'), ('Wild2', 'Wild2')], max_length=80)),
                ('token', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('builder', 'builder'), ('infantry', 'infantry'), ('pike', 'pike'), ('archer', 'archer'), ('cavalry', 'cavalry'), ('siege', 'siege'), ('monster', 'monster')], max_length=70)),
                ('health', models.PositiveIntegerField()),
                ('regenerate_time', models.PositiveIntegerField(default=43200)),
                ('damage', models.FloatField()),
                ('crash_bonus', models.PositiveIntegerField(default=0)),
                ('speed', models.FloatField()),
                ('infantry_attack_bonus', models.PositiveIntegerField(default=1)),
                ('infantry_defence_bonus', models.PositiveIntegerField(default=1)),
                ('pike_attack_bonus', models.PositiveIntegerField(default=1)),
                ('pike_defence_bonus', models.PositiveIntegerField(default=1)),
                ('archer_attack_bonus', models.PositiveIntegerField(default=1)),
                ('archer_defence_bonus', models.PositiveIntegerField(default=1)),
                ('cavalry_attack_bonus', models.PositiveIntegerField(default=1)),
                ('cavalry_defence_bonus', models.PositiveIntegerField(default=1)),
                ('monster_attack_bonus', models.PositiveIntegerField(default=1)),
                ('monster_defence_bonus', models.PositiveIntegerField(default=1)),
                ('summon_amount', models.PositiveIntegerField(default=0)),
                ('summon_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.troops')),
            ],
        ),
        migrations.CreateModel(
            name='UserHeroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dead', models.BooleanField(default=False)),
                ('regenerate_time_left', models.PositiveIntegerField(default=0)),
                ('last_checkout', models.DateTimeField(auto_now_add=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.heroes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
