# Generated by Django 4.1.6 on 2023-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_userheroes_current_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='userheroes',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
