# Generated by Django 4.1.6 on 2023-03-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_userheroes_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userheroes',
            name='current_health',
            field=models.PositiveIntegerField(),
        ),
    ]
