# Generated by Django 4.1.6 on 2023-03-12 22:26a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_userheroes_current_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userheroes',
            name='current_health',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
