# Generated by Django 4.1.6 on 2023-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_statistic_archer_dead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='hero_dead',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='hero_kill',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
