# Generated by Django 4.1.6 on 2023-04-06 10:35a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_statistic_hero_dead_statistic_hero_kill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userheroes',
            name='is_home',
            field=models.BooleanField(default=True),
        ),
    ]
