# Generated by Django 4.1.6 on 2023-04-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0001_initial'),
        ('main', '0042_alter_heroes_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliances.alliances'),
        ),
    ]
