# Generated by Django 4.1.6 on 2023-04-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_profile_alliance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
