# Generated by Django 4.1.6 on 2023-04-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='token',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
