# Generated by Django 4.1.6 on 2023-04-15 16:12a

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0046_resources_rings_wilddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('Wood', 'Wood'), ('Stone', 'Stone'), ('Iron', 'Iron'), ('Grain', 'Grain')], max_length=50)),
                ('offer_amount', models.PositiveIntegerField()),
                ('target_type', models.CharField(choices=[('Wood', 'Wood'), ('Stone', 'Stone'), ('Iron', 'Iron'), ('Grain', 'Grain')], max_length=50)),
                ('target_amount', models.PositiveIntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('offer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_user', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMarkets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_capacity', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Market',
        ),
    ]
