# Generated by Django 4.1.6 on 2023-04-15 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_rename_target_user_exchanges_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 15, 18, 44, 16, 862306, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchanges',
            name='offer_type',
            field=models.CharField(choices=[('wood', 'Wood'), ('stone', 'Stone'), ('iron', 'Iron'), ('grain', 'Grain')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exchanges',
            name='target_type',
            field=models.CharField(choices=[('wood', 'Wood'), ('stone', 'Stone'), ('iron', 'Iron'), ('grain', 'Grain')], max_length=50),
        ),
    ]
