# Generated by Django 4.1.6 on 2023-04-16 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_exchanges_added_time_alter_exchanges_offer_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wilddata',
            old_name='last_checkout',
            new_name='resource_last_checkout',
        ),
        migrations.AddField(
            model_name='wilddata',
            name='troop_last_checkout',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 4, 16, 17, 22, 12, 297879, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
