# Generated by Django 4.1.6 on 2023-04-17 20:51a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_wilddata_troop_last_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='rings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='the_one_ring',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
