# Generated by Django 4.1.6 on 2023-04-17 20:52a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_heroes_rings_heroes_the_one_ring'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='the_one_ring',
            field=models.BooleanField(default=False),
        ),
    ]
