# Generated by Django 4.1.6 on 2023-04-18 18:09a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_superpower_superpowerreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='superpower',
            name='power_damage',
            field=models.PositiveIntegerField(default=20000),
        ),
    ]
