# Generated by Django 4.1.6 on 2023-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_superpower_power_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='superpowerreports',
            name='revealed_attack_level',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='superpowerreports',
            name='revealed_defence_level',
            field=models.FloatField(default=1.0),
        ),
    ]
