# Generated by Django 4.1.6 on 2023-04-30 20:28a

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_superpower_last_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpower',
            name='last_checkout',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 20, 28, 39, 780420, tzinfo=datetime.timezone.utc)),
        ),
    ]
