# Generated by Django 4.1.6 on 2023-04-30 21:23a

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_superpower_last_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpower',
            name='last_checkout',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 21, 23, 42, 68266, tzinfo=datetime.timezone.utc)),
        ),
    ]
