# Generated by Django 4.1.6 on 2023-05-01 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_superpower_last_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='superpower',
            name='last_checkout',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 16, 46, 32, 410504, tzinfo=datetime.timezone.utc)),
        ),
    ]
