# Generated by Django 4.1.6 on 2023-05-02 18:14a

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_superpower_last_checkout_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpower',
            name='last_checkout',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 18, 14, 49, 400793, tzinfo=datetime.timezone.utc)),
        ),
    ]
