# Generated by Django 4.1.6 on 2023-05-03 07:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_marketsent_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superpower',
            name='last_checkout',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 7, 43, 54, 392182, tzinfo=datetime.timezone.utc)),
        ),
    ]
