# Generated by Django 4.1.6 on 2023-05-05 16:55a

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_marketsent_timestamp_alter_superpower_last_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='description',
            field=models.CharField(default=' ', max_length=140),
        ),
        migrations.AlterField(
            model_name='superpower',
            name='last_checkout',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 16, 55, 17, 213559, tzinfo=datetime.timezone.utc)),
        ),
    ]
