# Generated by Django 4.1.6 on 2023-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_alter_buildings_race_alter_heroes_the_one_ring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='race',
            field=models.CharField(choices=[('Men', 'Men'), ('Elves', 'Elves'), ('Dwarves', 'Dwarves'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor'), ('Goblins', 'Goblins'), ('Wild', 'Wild'), ('Good', 'Good'), ('Evil', 'Evil')], max_length=80),
        ),
        migrations.AlterField(
            model_name='superpower',
            name='last_checkout',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
