# Generated by Django 4.1.6 on 2023-05-11 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0074_alter_heroes_race_alter_superpower_last_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Men', 'Men'), ('Elves', 'Elves'), ('Dwarves', 'Dwarves'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor'), ('Goblins', 'Goblins'), ('Wild', 'Wild'), ('Evil', 'Evil')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resources',
            name='grain',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='resources',
            name='iron',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='resources',
            name='stone',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='resources',
            name='wood',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
