# Generated by Django 4.1.6 on 2023-03-01 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0031_alter_buildings_race_alter_troops_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartingTroops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('time_left', models.PositiveIntegerField(default=0)),
                ('last_checkout', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertroops')),
            ],
        ),
        migrations.CreateModel(
            name='ArrivingTroops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('time_left', models.PositiveIntegerField(default=0)),
                ('last_checkout', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertroops')),
            ],
        ),
    ]
