# Generated by Django 4.1.6 on 2023-03-01 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_buildings_race_alter_troops_race'),
        ('encampment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivingtroops',
            name='target_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
        migrations.AddField(
            model_name='departingtroops',
            name='target_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
    ]
