# Generated by Django 4.1.6 on 2023-03-02 11:07a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encampment', '0003_remove_arrivingtroops_last_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departingcampaigns',
            name='auto',
            field=models.BooleanField(default=True),
        ),
    ]
