# Generated by Django 4.1.6 on 2023-03-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encampment', '0004_departingcampaigns_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='departingtroops',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
