# Generated by Django 4.1.6 on 2023-03-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encampment', '0006_defenceposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivingcampaigns',
            name='campaign_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='departingcampaigns',
            name='campaign_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
