# Generated by Django 4.1.6 on 2023-03-27 21:48a

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_statistic_hero_dead_statistic_hero_kill'),
        ('encampment', '0007_arrivingcampaigns_campaign_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinforcementTroops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertroops')),
            ],
        ),
    ]
