# Generated by Django 4.1.6 on 2023-03-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encampment', '0008_reinforcementtroops'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivingcampaigns',
            name='arriving_grain',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arrivingcampaigns',
            name='arriving_iron',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arrivingcampaigns',
            name='arriving_stone',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arrivingcampaigns',
            name='arriving_wood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arrivingcampaigns',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departingcampaigns',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
