# Generated by Django 4.1.6 on 2023-03-31 16:08a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_statistic_hero_dead_statistic_hero_kill'),
        ('encampment', '0009_arrivingcampaigns_arriving_grain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivingtroops',
            name='user_troop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usertroops'),
        ),
    ]
