# Generated by Django 4.1.6 on 2023-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encampment', '0011_departingcampaigns_arriving_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivingcampaigns',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='arrivingcampaigns',
            name='arriving_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
