# Generated by Django 4.1.6 on 2023-04-13 14:05a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_resources_token'),
        ('encampment', '0013_departingheroes_arrivingheroes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departingtroops',
            name='user_troop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usertroops'),
        ),
    ]
