# Generated by Django 4.1.6 on 2023-04-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encampment', '0014_alter_departingtroops_user_troop'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivingcampaigns',
            name='arriving_rings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
