# Generated by Django 4.1.6 on 2023-05-01 21:35a

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encampment', '0016_departingtasklogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departingtasklogs',
            name='last_call_time',
        ),
    ]
