# Generated by Django 4.1.6 on 2023-05-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encampment', '0017_remove_departingtasklogs_last_call_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartingTaskLogs',
        ),
    ]
