version: '3.9'

services:
  django_gunicorn:
    build: .
    volumes:
      - .:/app/
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn warofsix.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
    depends_on:
      - db
      

  celery:
    build: .
    volumes:
      - .:/app/
    command: celery -A warofsix worker -l INFO
    depends_on:
      - django_gunicorn
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=amqp://rabbitmq:5672

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    container_name: postgres_db


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
      - ./rabbitmq_advanced.config:/etc/rabbitmq/advanced.config
    ports:
      - 5672:5672

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  pgdata:
  rabbitmq_data:
  rabbitmq_log:
