# Generated by Django 4.1.6 on 2023-03-02 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0031_alter_buildings_race_alter_troops_race'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.BooleanField(default=True)),
                ('attacker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacker', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefenderDeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.PositiveIntegerField(default=0)),
                ('deads', models.PositiveIntegerField(default=0)),
                ('battle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.battles')),
                ('troop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.troops')),
            ],
        ),
        migrations.CreateModel(
            name='AttackerDeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.PositiveIntegerField(default=0)),
                ('deads', models.PositiveIntegerField(default=0)),
                ('battle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.battles')),
                ('troop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.troops')),
            ],
        ),
    ]
