# Generated by Django 4.1.6 on 2023-03-26 00:23a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_statistic_hero_dead_statistic_hero_kill'),
        ('battle', '0002_battles_time_alter_attackerdeads_troop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attackerdeads',
            old_name='current',
            new_name='troop_count',
        ),
        migrations.RenameField(
            model_name='attackerdeads',
            old_name='troop',
            new_name='user_troop',
        ),
        migrations.RenameField(
            model_name='defenderdeads',
            old_name='current',
            new_name='troop_count',
        ),
        migrations.RenameField(
            model_name='defenderdeads',
            old_name='troop',
            new_name='user_troop',
        ),
        migrations.RemoveField(
            model_name='battles',
            name='attacker',
        ),
        migrations.RemoveField(
            model_name='battles',
            name='defender',
        ),
        migrations.AddField(
            model_name='attackerdeads',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attackerdeads',
            name='status',
            field=models.CharField(default='dead', max_length=20),
        ),
        migrations.AddField(
            model_name='attackerdeads',
            name='user_hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userheroes'),
        ),
        migrations.AddField(
            model_name='attackerdeads',
            name='user_hero_troop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.troops'),
        ),
        migrations.AddField(
            model_name='attackerdeads',
            name='user_hero_troop_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attackerdeads',
            name='user_hero_troop_dead',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defenderdeads',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defenderdeads',
            name='status',
            field=models.CharField(default='dead', max_length=20),
        ),
        migrations.AddField(
            model_name='defenderdeads',
            name='user_hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userheroes'),
        ),
        migrations.AddField(
            model_name='defenderdeads',
            name='user_hero_troop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.troops'),
        ),
        migrations.AddField(
            model_name='defenderdeads',
            name='user_hero_troop_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defenderdeads',
            name='user_hero_troop_dead',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
