# Generated by Django 4.1.6 on 2023-04-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_statistic_hero_dead_statistic_hero_kill'),
        ('battle', '0004_battles_attacker_battles_defender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenderBuildingDemolish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_battle_level', models.PositiveIntegerField()),
                ('post_battle_level', models.PositiveIntegerField()),
                ('battle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.battles')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.buildings')),
            ],
        ),
    ]
