# Generated by Django 4.1.6 on 2023-04-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_defenderbuildingdemolish'),
    ]

    operations = [
        migrations.AddField(
            model_name='battles',
            name='attacker_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battles',
            name='defender_is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
