# Generated by Django 4.1.6 on 2023-04-30 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_battles_attacker_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlePillageResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood', models.PositiveIntegerField(default=0)),
                ('stone', models.PositiveIntegerField(default=0)),
                ('iron', models.PositiveIntegerField(default=0)),
                ('grain', models.PositiveIntegerField(default=0)),
                ('rings', models.PositiveIntegerField(default=0)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.battles')),
            ],
        ),
    ]
