# Generated by Django 4.1.6 on 2023-05-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0008_battles_battle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='battles',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
