# Generated by Django 4.1.6 on 2023-04-11 22:30a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_resources_token'),
        ('alliances', '0006_alliancedepartingcampaign_alliancedepartingtroops_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllianceDeoartingHeroes',
            new_name='AllianceDepartingHeroes',
        ),
        migrations.AddField(
            model_name='alliancedepartingcampaign',
            name='alliance',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='alliances.alliances'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alliancedepartingcampaign',
            name='creator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliances.alliancemembers'),
        ),
    ]
