# Generated by Django 4.1.6 on 2023-04-12 13:06a

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0007_rename_alliancedeoartingheroes_alliancedepartingheroes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancedepartingcampaign',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 12, 13, 6, 41, 277324, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
